################################# Default configuration ###################
DefaultContentLanguage = "de"
baseURL = "https://solziv.netlify.app/"
disableLanguages = []
disqusShortname = ""
paginate = "4"
summaryLength = "30"
theme = "airspace-hugo"
title = "SolZiv | Potenziale der Zivilgesellschaft"

#################################### Plugins ##############################

[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"

############################### widgets #################################
[params.widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]

#################### default parameters ################################
[params]
author = "SolZiv"
contact_form_action = "#"
description = "Potenziale der Zivilgesellschaft"
email = "solziv2020@gmail.com"
google_analitycs_id = "UA-168222438-1"
location = "Berlin, Germany"
logo = "images/SolZiv_logo/Original on Transparent_small.png"
mobile = "0124857985320"
multi_author = false

# google map
[params.gmap]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "52.5162778"
map_longitude = "13.3755154"
map_marker = "images/marker.png"

# Navigation get start button
[params.nav_button]
enable = true
label = "Get A Quote"
link = "contact"

# Preloader
[params.preloader]
enable = true
preloader = ""

############################# social site ########################
[[params.social]]
icon = "ion-social-googleplus-outline"
link = "#"
[[params.social]]
icon = "ion-social-linkedin-outline"
link = "#"
[[params.social]]
icon = "ion-social-pinterest-outline"
link = "#"
[[params.social]]
icon = "ion-social-dribbble-outline"
link = "#"
[[params.social]]
icon = "ion-social-twitter-outline"
link = "#"
[[params.social]]
icon = "ion-social-facebook-outline"
link = "#"

################################ German Language ########################
[languages.de]
contentDir = "content/german"
copyright = "Copyright &copy; 2020 [Themefisher](https://themefisher.com) All Rights Reserved"
home = "home"
languageCode = "de-de"
languageName = "De"
weight = "1"
# german menu

# main menu
[[languages.de.menu.main]]
name = "Projekt"
URL = "about"
weight = 1

[[languages.de.menu.main]]
URL = "service"
name = "Team"
weight = 2

[[languages.de.menu.main]]
URL = "blog"
name = "Blog"
weight = 3

[[languages.de.menu.main]]
URL = "contact"
name = "Kontakt"
weight = 4

# footer menu

[[languages.de.menu.footer]]
URL = "about"
name = "Projekt"
weight = 1

[[languages.de.menu.footer]]
URL = "service"
name = "Team"
weight = 2
[[languages.de.menu.footer]]
URL = "blog"
name = "Blog"
weight = 3
[[languages.de.menu.footer]]
URL = "contact"
name = "Kontakt"
weight = 4

################################ English Language ########################
[languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2020 [Themefisher](https://themefisher.com) All Rights Reserved"
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = "2"

# main menu
[[languages.en.menu.main]]
name = "Project"
URL = "about"
weight = 1

[[languages.en.menu.main]]
URL = "service"
name = "Team"
weight = 2

[[languages.en.menu.main]]
URL = "blog"
name = "Blog"
weight = 3

[[languages.en.menu.main]]
URL = "contact"
name = "Contact"
weight = 4


# footer menu

[[languages.en.menu.footer]]
URL = "about"
name = "Project"
weight = 1

[[languages.en.menu.footer]]
URL = "service"
name = "Team"
weight = 2
[[languages.en.menu.footer]]
URL = "blog"
name = "Blog"
weight = 3
[[languages.en.menu.footer]]
URL = "contact"
name = "Contact"
weight = 4


